#!/bin/bash
# 
# A Fast way to spin me up a instance named after beautiful woman
# Faq:
#	this is a bootstrap tool for one or more instances 

#env defines
export AWS_DEFAULT_REGION=us-east-1
use_key=key
use_sg=aws

#funcs
function info {
	for g in aj stoya 
	do
        	ip=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$g" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text) 
		if [ ! -z $ip ] ;then
			echo "> I've found $g running with ip $ip" 
		fi
	done	
}
function kill_gal {
id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$1" --query 'Reservations[*].Instances[*].InstanceId' --output text |head -1)
if [ ! -z $id ] ; then 
    echo ">terminanting $id, she had a good one!"
    aws ec2 terminate-instances --instance-ids $id
else 
    echo ">could not find instanced named $1"
fi
    }

    function spin_up_a_gal {
    gal=$1
    ip=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$gal" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text | head -1)
    if [ ! -z $ip ]; then
        echo ">Found $gal on us-east-1, alive and kicking!"
        echo ">Penetrating $gal..."
        ssh ec2-user@$ip
    else
        echo "Coul not find $gal...starting one"
        id=`aws ec2 run-instances --instance-type t2.micro --image-id ami-a4827dc9 --security-groups $use_sg --key-name $use_key --iam-instance-profile Name="ec2instance" --region us-east-1 --query 'Instances[*].InstanceId' --output text`
        echo -n "$gal launched with id $id ..."
        aws ec2 create-tags --resources $id --tags Key="Name",Value="$gal"
        ip=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$gal" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text) 
        echo "and ip $ip"  
    fi
}

#main
case $(basename $0) in
    "gimme")
        case $1 in

            "aj")
                # AJ Applegate lives in Virginia
                spin_up_a_gal aj us-east-1
                ;;
            "stoya")
                # Stoya lives in Sao Paulo
                spin_up_a_gal stoya sa-east-1
                ;;
            *)
                echo "Usage: $(basename $0) [aj|stoya]" 
                echo "       AJ Applegate lives in us-east-1 and Stoya in sa-east-1."
                ;;
        esac
        ;;
    "kill")
	kill_gal $1
	;;
    "stilleto")
        case $1 in
            "info")
		info
                ;;
            *)
                echo "Usage: $(basename $0) info" 
                ;;
        esac
        ;;
    *)
                echo "Usage: $(basename $0) [aj|stoya]" 
                echo "       AJ Applegate lives in us-east-1 and Stoya in sa-east-1."
                ;;
esac
